[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "VITE_OPENAI_API_KEY,VITE_OPENAI_ORG_ID,VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY" 